/* HANGOVER locker room — lazy collections, real originals and local engine exports. */
(function(){
'use strict';
const root=document.getElementById('library'),data=window.HANGOVER_LIBRARY;if(!root)return;
const $=id=>root.querySelector('#'+id),el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const lockers=$('libraryLockers'),panel=$('libraryPanel'),grid=$('libraryGrid'),search=$('librarySearch'),more=$('libraryMore'),dialog=$('libraryDialog'),art=$('libraryDialogArt'),pngButton=$('libraryPNG'),originalLink=$('libraryOriginal'),studioButton=$('libraryStudio');
if(!data||!Array.isArray(data.collections)||!Array.isArray(data.items)){$('libraryStatus').textContent='La raccolta non è disponibile. Ricarica la pagina per riprovare.';return;}
const extraDownloads=el('div','library-downloads library-extra-downloads');$('libraryDialogStatus').parentNode.append(extraDownloads);
const collections=data.collections,items=data.items,itemMap=new Map(items.map(x=>[String(x.id),x])),batch=12;
let currentCollection=null,visible=batch,collectionRevision=0,dialogRevision=0,lastLocker=null,lastCard=null,activeItem=null,busy=false,motionEngine=null;
const reduced=()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const scroll=node=>node.scrollIntoView({behavior:reduced()?'auto':'smooth',block:'start'});
function source(value){if(typeof value!=='string'||!value.trim())return null;try{const url=new URL(value,document.baseURI);return ['http:','https:','file:'].includes(url.protocol)&&(url.protocol==='file:'||url.origin===location.origin)?url.href:null;}catch(_){return null;}}
const svgFile=value=>typeof value==='string'&&/\.svg(?:[?#]|$)/i.test(value);
const slug=value=>String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9_-]+/gi,'-').replace(/^-|-$/g,'').slice(0,85)||'visual';
const filename=(item,extension)=>'HANGOVER-'+slug(item.title||item.id)+'.'+extension;
function save(blob,name){const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function luminance(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((sum,v,i)=>sum+v*[.2126,.7152,.0722][i],0);}
function lockerColor(value){const bg=typeof value==='string'&&/^#[0-9a-f]{6}$/i.test(value)?value:'#063c9a',l=luminance(bg);return {bg,ink:(1.05/(l+.05))>((l+.05)/.05)?'#ffffff':'#000000'};}
function message(text){return el('span','library-art-message',text);}
function generatedSVG(item,uid){if(item.renderer==='objects'&&window.HangoverObjects)return window.HangoverObjects.render(item.renderId,{uid});if(item.renderer==='signage'&&window.HangoverSignage)return window.HangoverSignage.render(item.renderId,{uid});if(item.renderer==='maker'&&window.HangoverMakerEngine)return window.HangoverMakerEngine.render(item.config,{uid});throw Error('Il disegno non è disponibile. Apri lo studio per riprovare.');}
async function motionCanvas(item,longEdge,preview=false){
 if(!window.createHangoverStudio||!window.HANGOVER_STUDIO_DATA)throw Error('Apri Motion Studio per vedere questo movimento.');
 if(!motionEngine)motionEngine=window.createHangoverStudio(window.HANGOVER_STUDIO_DATA);
 await motionEngine.ready;
 const preset=window.HANGOVER_STUDIO_DATA.presets.find(p=>p.id===item.renderId);if(!preset)throw Error('Preset Motion non disponibile.');
 const cfg={preset:preset.id,palette:preset.palette||'ice',format:preset.format||'9:16',photo:preset.photo||'01',title:'ALL NIGHT',subtitle:'HANGOVER / AFTER DARK',lineup:'[ARTISTA 01]\n[ARTISTA 02]\n[ARTISTA 03]',duration:10,speed:1,effects:['grain'],customImage:null,...(item.config||{})};
 const dimensions=motionEngine.dimensions(cfg.format,1000),ratio=longEdge/Math.max(...dimensions),canvas=el('canvas');canvas.width=Math.round(dimensions[0]*ratio);canvas.height=Math.round(dimensions[1]*ratio);canvas.setAttribute('role','img');canvas.setAttribute('aria-label',item.title+' — fotogramma');
 const time=Number.isFinite(item.posterTime)?item.posterTime:2;if(preview&&motionEngine.preview)motionEngine.preview(canvas.getContext('2d'),canvas.width,canvas.height,time,cfg,{background:'checker'});else motionEngine.render(canvas.getContext('2d'),canvas.width,canvas.height,time,cfg);return canvas;
}
function imageNode(item,full){
 // A selected panel can have a viewport. The modal always shows the complete source board.
 if(!full&&item.viewport&&window.HangoverImage){const view=window.HangoverImage.create(item,source(item.src)||source(item.original));view.setAttribute('aria-hidden','true');return view;}
 const image=el('img');image.alt=full?item.title:'';image.loading=full?'eager':'lazy';image.decoding='async';image.draggable=false;const first=full?(source(item.original)||source(item.src)):(source(item.src)||source(item.original));if(!first)throw Error('Originale non disponibile.');image.src=first;
 image.addEventListener('error',()=>{const fallback=source(item.original);if(!full&&fallback&&image.src!==fallback){image.src=fallback;return;}image.replaceWith(message('Anteprima non disponibile. Puoi provare ad aprire l’originale.'));},{once:false});return image;
}
async function paintItem(item,target,{full=false,revision=collectionRevision}={}){
 const active=()=>full?(dialog.open&&revision===dialogRevision):(revision===collectionRevision&&target.isConnected);
 try{
  if(item.renderer==='objects'||item.renderer==='signage'||item.renderer==='maker'){const svg=generatedSVG(item,'library-'+(full?'detail-':'tile-')+revision+'-'+slug(item.id));if(active())target.innerHTML=svg;}
  else if(item.renderer==='motion'){const canvas=await motionCanvas(item,full?1200:420,true);if(active())target.replaceChildren(canvas);}
  else if(source(item.src)||source(item.original)){if(active())target.replaceChildren(imageNode(item,full));}
  else if(item.renderer==='section'){if(active())target.replaceChildren(message('Questa composizione vive nello studio. Aprila per esplorarla.'));}
  else throw Error('Anteprima non disponibile.');
 }catch(error){if(active())target.replaceChildren(message(error.message||'Anteprima non disponibile.'));}
 finally{if(full&&active())target.setAttribute('aria-busy','false');}
}
function subset(){const query=search.value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();return items.filter(i=>i.collection===currentCollection&&(!query||[i.title,i.kind,...(i.tags||[])].join(' ').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query)));}
function typeLabel(item){return item.renderer==='motion'?'Motion / fotogramma':item.renderer==='objects'?'Oggetto modificabile':item.renderer==='maker'?'Preset Object Maker':item.renderer==='signage'?'Segnaletica':item.renderer==='section'?'Studio interattivo':item.viewport?'Tavola / dettaglio':svgFile(item.original)?'Sorgente SVG':'Visual';}
function renderCards(){
 const revision=++collectionRevision,list=subset(),shown=list.slice(0,visible),total=items.filter(x=>x.collection===currentCollection).length;grid.replaceChildren();
 for(const item of shown){const b=el('button','library-card'),preview=el('span','library-card-art'),title=el('span','library-card-title',item.title),meta=el('span','library-card-meta');b.type='button';b.dataset.libraryItem=String(item.id);b.setAttribute('aria-label','Apri '+item.title);preview.setAttribute('aria-hidden','true');preview.append(message(item.renderer==='motion'?'Preparo il fotogramma…':'Apro il visual…'));meta.append(el('span','',typeLabel(item)),el('span','','↗'));b.append(preview,title,meta);b.addEventListener('click',()=>openItem(item,b));grid.append(b);paintItem(item,preview,{revision});}
 $('libraryCount').textContent=search.value.trim()?shown.length+' di '+list.length+' risultati · '+total+' nella collezione':shown.length+' di '+total+' materiali';$('libraryEmpty').hidden=list.length>0;more.hidden=list.length<=shown.length;more.textContent='Mostra altri '+Math.min(batch,list.length-shown.length)+' ↓';
}
function openCollection(id,button){const collection=collections.find(c=>c.id===id);if(!collection)return;currentCollection=id;lastLocker=button;visible=batch;search.value='';panel.hidden=false;$('libraryBreadcrumb').textContent=collection.title;$('libraryCollectionTitle').textContent=collection.title;$('libraryCollectionSubtitle').textContent=collection.subtitle||'';lockers.querySelectorAll('button').forEach(b=>b.setAttribute('aria-expanded',String(b===button)));renderCards();$('libraryCollectionTitle').focus({preventScroll:true});scroll(panel);}
function closeCollection(){collectionRevision++;currentCollection=null;panel.hidden=true;grid.replaceChildren();lockers.querySelectorAll('button').forEach(b=>b.setAttribute('aria-expanded','false'));lastLocker?.focus({preventScroll:true});if(lastLocker)scroll(lastLocker);}
collections.forEach((collection,index)=>{
 const count=items.filter(i=>i.collection===collection.id).length,color=lockerColor(collection.color),button=el('button','library-locker'),top=el('span','library-locker-top'),bottom=el('span','library-locker-bottom'),sticker=el('img','library-sticker');button.type='button';button.style.setProperty('--locker-bg',color.bg);button.style.setProperty('--locker-ink',color.ink);button.dataset.libraryCollection=collection.id;button.setAttribute('aria-expanded','false');button.setAttribute('aria-controls','libraryPanel');button.setAttribute('aria-label',collection.title+', '+count+' materiali. Apri collezione.');top.append(el('span','library-locker-number',String(index+1).padStart(2,'0')),el('span','library-locker-count',count+' PEZZI'));sticker.src='assets/h.svg';sticker.alt='';sticker.setAttribute('aria-hidden','true');bottom.append(el('span','library-locker-open','APRI COLLEZIONE ↗'),sticker);const vents=el('span','library-vents'),handle=el('span','library-locker-handle');vents.setAttribute('aria-hidden','true');handle.setAttribute('aria-hidden','true');button.append(top,vents,el('span','library-locker-title',collection.title),el('span','library-locker-subtitle',collection.subtitle||''),handle,bottom);button.addEventListener('click',()=>openCollection(collection.id,button));lockers.append(button);
});
$('libraryTotal').textContent=collections.length+' armadietti / '+items.length+' materiali';
$('libraryCloseCollection').addEventListener('click',closeCollection);search.addEventListener('input',()=>{visible=batch;renderCards();});more.addEventListener('click',()=>{visible+=batch;renderCards();});$('libraryClearSearch').addEventListener('click',()=>{search.value='';visible=batch;renderCards();search.focus();});
function openItem(item,button){
 activeItem=item;lastCard=button;const revision=++dialogRevision;art.replaceChildren(message('Preparo l’anteprima…'));art.setAttribute('aria-busy','true');$('libraryDialogTitle').textContent=item.title;$('libraryDialogCollection').textContent=collections.find(c=>c.id===item.collection)?.title||'HANGOVER';$('libraryDialogStatus').textContent='';
 const vector=item.renderer==='objects'||item.renderer==='signage'||item.renderer==='maker',motion=item.renderer==='motion',staticSVG=svgFile(item.original),original=source(item.original);
 originalLink.hidden=!vector&&!original;originalLink.textContent=vector?'Scarica SVG ↘':motion?'Scarica preset JSON ↘':'Scarica originale ↘';originalLink.href=original||'#';originalLink.download=filename(item,vector?'svg':(item.original||'').split(/[?#]/)[0].split('.').pop()||'png');
 const video=source(item.videoSrc),videoLink=$('libraryVideoOriginal');videoLink.hidden=!video;if(video){videoLink.href=video;videoLink.download=filename(item,(item.videoSrc||'').split(/[?#]/)[0].split('.').pop()||'webm');}
 extraDownloads.replaceChildren();const alternatives=[...(item.svg&&item.svg!==item.original?[{label:'SVG originale',src:item.svg}]:[]),...(Array.isArray(item.downloads)?item.downloads:[])],seen=new Set([original]);for(const file of alternatives){const href=source(file.src);if(!href||seen.has(href))continue;seen.add(href);const link=el('a','',file.label+' ↘');link.href=href;link.download=String(file.src).split(/[?#]/)[0].split('/').pop();extraDownloads.append(link);}
 pngButton.hidden=!(vector||motion||staticSVG||item.viewport);pngButton.disabled=busy;pngButton.textContent=motion?'Scarica fotogramma PNG ↘':item.viewport?'Scarica il riquadro PNG ↘':'Scarica PNG ↘';studioButton.hidden=!(item.renderer||item.studioHref);studioButton.textContent=item.renderer==='objects'||item.renderer==='maker'?'Personalizzalo ↗':motion?'Apri Motion Studio ↗':item.renderer==='signage'?'Personalizza la direzione ↗':'Apri lo studio ↗';
 $('libraryDialogNote').textContent=motion?'Fotogramma del movimento. Il PNG conserva la trasparenza disponibile nel preset; per video, risoluzione e sequenze apri Motion Studio.':vector?'SVG vettoriale originale del modello. PNG renderizzato a 2400 px sul lato lungo. Per cambiare testi e colori, apri lo studio.':item.viewport?'Anteprima della tavola completa. Scarica l’originale oppure il singolo riquadro PNG, alla risoluzione disponibile.':item.renderer==='section'?'Composizione interattiva: apri lo studio per vederla e usare i controlli disponibili.':staticSVG?'File SVG originale. Puoi anche scaricare una versione PNG a 2400 px sul lato lungo.':'Immagine intera, senza ritagli. Scarichi il file originale alla sua risoluzione.';
 dialog.showModal();document.body.classList.add('modal-open');$('libraryDialogClose').focus();paintItem(item,art,{full:true,revision});
}
$('libraryDialogClose').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target!==dialog)return;const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();});
dialog.addEventListener('close',()=>{if(dialog.open)return;dialogRevision++;art.replaceChildren();art.setAttribute('aria-busy','false');activeItem=null;if(!document.querySelector('dialog[open]'))document.body.classList.remove('modal-open');if(lastCard?.isConnected)lastCard.focus({preventScroll:true});});
root.addEventListener('keydown',event=>{if(event.key==='Escape'&&!dialog.open&&!panel.hidden){event.preventDefault();closeCollection();}});
originalLink.addEventListener('click',event=>{const item=activeItem;if(!item)return;if(item.renderer==='objects'||item.renderer==='signage'||item.renderer==='maker'){event.preventDefault();try{save(new Blob([generatedSVG(item,'library-export-'+slug(item.id))],{type:'image/svg+xml'}),filename(item,'svg'));$('libraryDialogStatus').textContent='SVG pronto.';}catch(error){$('libraryDialogStatus').textContent=error.message;}}});
async function pngFromSVG(item){let address,temporary=false;
 if(item.renderer==='objects'||item.renderer==='signage'||item.renderer==='maker'){address=URL.createObjectURL(new Blob([generatedSVG(item,'library-png-'+slug(item.id))],{type:'image/svg+xml'}));temporary=true;}else address=source(item.original);
 try{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('PNG non disponibile. Puoi scaricare lo SVG originale.'));image.src=address;});const width=image.naturalWidth||item.width,height=image.naturalHeight||item.height;if(!(width>0&&height>0))throw Error('Dimensioni del disegno non disponibili.');const canvas=el('canvas');if(item.viewport){const v=item.viewport,sx=v.x*width/v.sourceWidth,sy=v.y*height/v.sourceHeight,sw=v.width*width/v.sourceWidth,sh=v.height*height/v.sourceHeight;if(![sx,sy,sw,sh].every(Number.isFinite)||sw<=0||sh<=0||sx<0||sy<0||sx+sw>width+.5||sy+sh>height+.5)throw Error('Riquadro non disponibile. Scarica la tavola originale.');canvas.width=Math.max(1,Math.round(sw));canvas.height=Math.max(1,Math.round(sh));canvas.getContext('2d').drawImage(image,sx,sy,sw,sh,0,0,canvas.width,canvas.height);}else{const scale=2400/Math.max(width,height);canvas.width=Math.round(width*scale);canvas.height=Math.round(height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);}return canvas;}finally{if(temporary)URL.revokeObjectURL(address);}
}
pngButton.addEventListener('click',async()=>{if(!activeItem||busy)return;const item=activeItem,revision=dialogRevision;busy=true;pngButton.disabled=true;$('libraryDialogStatus').textContent='Preparo il PNG…';try{const canvas=item.renderer==='motion'?await motionCanvas(item,1920):await pngFromSVG(item),blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Esportazione PNG non disponibile.')),'image/png'));save(blob,filename(item,item.renderer==='motion'?'frame.png':'png'));if(revision===dialogRevision)$('libraryDialogStatus').textContent='PNG pronto · '+canvas.width+' × '+canvas.height+' px.';}catch(error){if(revision===dialogRevision)$('libraryDialogStatus').textContent=error.message;}finally{busy=false;pngButton.disabled=false;}});
function studioTarget(item){
 if(item.renderer==='objects'){let button=document.querySelector('[data-object="'+CSS.escape(String(item.renderId))+'"]');if(!button){document.querySelector('#oggetti [data-object-filter="all"]')?.click();button=document.querySelector('[data-object="'+CSS.escape(String(item.renderId))+'"]');}if(button){button.click();return true;}}
 if(item.renderer==='maker'){const select=document.getElementById('makerPreset');if(select){select.value=item.renderId;select.dispatchEvent(new Event('change',{bubbles:true}));scroll(document.getElementById('maker'));select.focus({preventScroll:true});return true;}}
 if(item.renderer==='signage'){const select=document.getElementById('sgDesign');if(select){select.value=item.renderId;select.dispatchEvent(new Event('change',{bubbles:true}));scroll(document.getElementById('segnaletica'));select.focus({preventScroll:true});return true;}}
 if(item.renderer==='motion'){document.querySelector('[data-ml-filter="all"]')?.click();const button=document.querySelector('[data-ml-preset="'+CSS.escape(String(item.renderId))+'"]');if(button){button.click();button.focus({preventScroll:true});return true;}}
 if(item.renderer==='section'&&item.sourceSelector){try{const target=document.querySelector(item.sourceSelector);if(target){const state=item.previewState||{};if(['chrome','echo','cut'].includes(state.effect))document.querySelector('[data-motion="'+state.effect+'"]')?.click();if(Number.isInteger(state.slide)&&state.slide>=0&&state.slide<4){const current=Number.parseInt(document.getElementById('carouselCount')?.textContent,10)-1;if(Number.isFinite(current))for(let i=0;i<(state.slide-current+4)%4;i++)document.getElementById('carouselNext')?.click();}scroll(target);target.setAttribute('tabindex','-1');target.focus({preventScroll:true});return true;}}catch(_){/* Fall back to the source section when a legacy selector is unavailable. */}}
 const href=typeof item.studioHref==='string'&&/^#[\w-]+$/.test(item.studioHref)?item.studioHref:(typeof item.sourceSection==='string'?(item.sourceSection.startsWith('#')?item.sourceSection:'#'+item.sourceSection):null),target=href&&document.getElementById(href.slice(1));if(target){scroll(target);const focus=target.querySelector('button,input,select,a[href]')||target;if(!focus.hasAttribute('tabindex')&&focus===target)focus.setAttribute('tabindex','-1');focus.focus({preventScroll:true});return true;}return false;
}
studioButton.addEventListener('click',()=>{const item=activeItem;if(!item)return;dialog.close();setTimeout(()=>{if(!studioTarget(item)){$('libraryStatus').textContent='Lo studio non è ancora pronto. Riprova tra poco.';lastCard?.focus({preventScroll:true});}},0);});
window.HangoverLibrary={openCollection(id){const button=lockers.querySelector('[data-library-collection="'+CSS.escape(String(id))+'"]');if(button)openCollection(id,button);},openItem(id){const item=itemMap.get(String(id));if(item)openItem(item,document.activeElement);},counts(){return {collections:collections.length,items:items.length,visible:grid.children.length};}};
})();
