(function(){
'use strict';
const root=document.querySelector('#maker'),D=window.HangoverMakerData,E=window.HangoverMakerEngine;if(!root||!D||!E)return;
const q=s=>root.querySelector(s),qa=s=>Array.from(root.querySelectorAll(s)),status=q('#makerStatus'),preview=q('#makerPreview'),form=q('form'),history=[];
let state=D.normalize(D.defaults),samples=[],sampleSeed=1,pending=0,sampleTimer=0,exporting=false;
const snapshot=()=>JSON.stringify(state),name=(list,id)=>list.find(x=>x.id===id)?.name||id;
function remember(){const last=snapshot();if(history.at(-1)!==last)history.push(last);if(history.length>30)history.shift();q('#makerUndo').disabled=!history.length;}
function options(el,list){el.replaceChildren(...list.map(item=>{const o=document.createElement('option');o.value=item.id;o.textContent=item.name;return o;}));}
for(const [id,list] of Object.entries({makerType:D.types,makerFont:D.fonts,makerMood:D.moods,makerContext:D.contexts,makerLayout:D.layouts,makerEffect:D.effects}))options(q('#'+id),list);
for(const preset of D.presets){const o=document.createElement('option');o.value=preset.id;o.textContent=preset.name;q('#makerPreset').append(o);}
for(const palette of D.palettes){const b=document.createElement('button');b.type='button';b.dataset.makerPalette=palette.id;b.setAttribute('aria-label',palette.name);b.title=palette.name;for(const key of ['bg','fg','accent']){const span=document.createElement('span');span.style.backgroundColor=palette[key];b.append(span);}q('#makerPalettes').append(b);}
function shapeOptions(){const type=D.types.find(t=>t.id===state.type);options(q('#makerShape'),D.shapes.filter(s=>type.shapes.includes(s.id)));q('#makerTypeNote').textContent=type.description||`${type.mmw} × ${type.mmh} mm`;}
function sync(preserveInput=false){shapeOptions();qa('[data-maker-field]').forEach(el=>{if(preserveInput&&document.activeElement===el)return;if(el.type==='checkbox')el.checked=state[el.dataset.makerField];else el.value=state[el.dataset.makerField];});q('#makerIntensityValue').value=state.effect==='flat'?'—':state.intensity+'%';q('#makerIntensity').disabled=state.effect==='flat';qa('[data-maker-palette]').forEach(b=>{const p=D.palettes.find(x=>x.id===b.dataset.makerPalette);b.setAttribute('aria-pressed',String(['bg','fg','accent'].every(k=>p[k].toLowerCase()===state[k].toLowerCase())));});q('#makerUndo').disabled=!history.length;}
function contrast(a,b){const l=c=>{const [r,g,b]=[1,3,5].map(i=>parseInt(c.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*r+.7152*g+.0722*b;};const x=l(a),y=l(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
function qrState(){
 const base=E.info({...state,qrEnabled:false});
 if(!base.qrAvailable&&state.qrEnabled){state.qrEnabled=false;q('#makerQrEnabled').checked=false;}
 q('#makerQrEnabled').disabled=!base.qrAvailable;q('#makerQrURLLabel').hidden=!state.qrEnabled;
 q('#makerQrNote').textContent=base.qrAvailable?'Il codice apre direttamente il link inserito. Nessuna scadenza del QR.':base.qrReason;
 q('#makerQrURL').removeAttribute('aria-invalid');
 try{if(state.qrEnabled)window.HangoverQR.validate(state.qrURL);return {valid:true,info:E.info(state)};}
 catch(error){q('#makerQrURL').setAttribute('aria-invalid','true');q('#makerQrNote').textContent=error.message;return {valid:false,info:base};}
}
function paint(){pending=0;try{const result=qrState(),info=result.info;preview.innerHTML=E.render(result.valid?state:{...state,qrEnabled:false},{uid:'maker-live'});qa('[data-maker-export]').forEach(b=>b.disabled=exporting||!result.valid);q('#makerFormat').textContent=name(D.types,state.type);q('#makerDimensions').textContent=`${info.mmw} × ${info.mmh} mm`;q('#makerTreatment').textContent=`${name(D.shapes,state.shape)} / ${name(D.effects,state.effect)}`;const unsupported=info.unsupported||[];q('#makerHint').textContent=!result.valid?'Correggi il link per aggiungere il QR e scaricare il disegno.':info.qrWarning|| (unsupported.length&&state.font==='display'?`Il lettering non contiene ${unsupported.join(' ')}. Sostituisci questi caratteri oppure scegli Sans o Mono.`:contrast(state.bg,state.fg)<1.6?'Segno e fondo sono molto simili: cambia un colore per far risaltare la scritta.':'');}catch(e){qa('[data-maker-export]').forEach(b=>b.disabled=true);status.textContent='Anteprima non disponibile. Prova un altro preset.';}}
function schedule(){if(pending)cancelAnimationFrame(pending);pending=requestAnimationFrame(paint);}
function proposals(){clearTimeout(sampleTimer);sampleTimer=0;if(!qrState().valid){samples=[];q('#makerSamples').textContent='Le proposte riprendono appena il link è valido.';return;}samples=D.suggest(state,sampleSeed,4);q('#makerSamples').replaceChildren();q('#makerSuggestionsContext').textContent=`${name(D.contexts,state.context)} / ${name(D.moods,state.mood)}`;for(const [index,sample] of samples.entries()){const button=document.createElement('button');button.type='button';button.className='maker-sample';button.dataset.makerSample=String(index);button.setAttribute('aria-label','Usa proposta '+sample.name);button.setAttribute('aria-pressed','false');const art=document.createElement('span');art.className='maker-sample-art';art.setAttribute('aria-hidden','true');art.innerHTML=E.render(sample.state,{uid:'maker-sample-'+index});const label=document.createElement('span');label.className='maker-sample-name';label.textContent=sample.name;const desc=document.createElement('small');desc.textContent=`${name(D.layouts,sample.state.layout)} / ${name(D.effects,sample.state.effect)}`;label.append(desc);button.append(art,label);q('#makerSamples').append(button);}}
function changed(patch,{record=true,refresh=true,preserveInput=false}={}){if(record)remember();state=D.normalize({...state,...patch});q('#makerPreset').value='';sync(preserveInput);schedule();status.textContent='';if(refresh){clearTimeout(sampleTimer);sampleTimer=setTimeout(proposals,180);}}
form.addEventListener('submit',e=>e.preventDefault());
form.addEventListener('input',event=>{const input=event.target;if(!input.matches('[data-maker-field]'))return;const key=input.dataset.makerField;if(input.tagName==='SELECT')return;changed({[key]:input.type==='range'?Number(input.value):input.type==='checkbox'?input.checked:input.value},{preserveInput:true});});
form.addEventListener('change',event=>{const input=event.target;if(!input.matches('select[data-maker-field]'))return;const key=input.dataset.makerField,patch={[key]:input.value};if(key==='type'){const type=D.types.find(t=>t.id===input.value);patch.shape=type.defaultShape;}changed(patch);});
q('#makerPreset').addEventListener('change',event=>{const preset=D.presets.find(p=>p.id===event.target.value);if(!preset)return;remember();state=D.normalize({...D.defaults,...preset.state});sync();paint();proposals();status.textContent=preset.name+' — ora è tuo da modificare.';});
root.addEventListener('click',event=>{const palette=event.target.closest('[data-maker-palette]');if(palette){const p=D.palettes.find(x=>x.id===palette.dataset.makerPalette);changed({palette:p.id,bg:p.bg,fg:p.fg,accent:p.accent});return;}const button=event.target.closest('[data-maker-sample]');if(button){const selected=samples[Number(button.dataset.makerSample)];if(!selected)return;clearTimeout(sampleTimer);sampleTimer=0;const direction=Object.fromEntries(['layout','palette','bg','fg','accent','effect','intensity','seed'].map(key=>[key,selected.state[key]]));changed(direction,{refresh:false});qa('[data-maker-sample]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));status.textContent=selected.name+' applicata.';}});
q('#makerGenerate').addEventListener('click',()=>{sampleSeed++;proposals();status.textContent='Quattro nuove proposte. Scegline una per applicarla.';});
q('#makerUndo').addEventListener('click',()=>{if(!history.length)return;state=D.normalize(JSON.parse(history.pop()));sync();paint();proposals();q('#makerPreset').value='';status.textContent='Ultima modifica annullata.';});
q('#makerNew').addEventListener('click',()=>{remember();state=D.normalize(D.defaults);sampleSeed++;sync();paint();proposals();q('#makerPreset').value='';status.textContent='Nuovo oggetto pronto. Puoi tornare al precedente con Annulla.';});
function download(blob,filename){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function filename(){return 'HANGOVER-'+state.type+'-'+state.title.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,35).toLowerCase();}
async function png(svg,info){const address=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'})),img=new Image();try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('Il PNG non è disponibile: puoi scaricare lo stesso disegno in SVG.'));img.src=address;});const scale=3000/Math.max(info.width,info.height),canvas=document.createElement('canvas');canvas.width=Math.round(info.width*scale);canvas.height=Math.round(info.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('Esportazione PNG non disponibile.');return blob;}finally{URL.revokeObjectURL(address);}}
root.addEventListener('click',async event=>{const button=event.target.closest('[data-maker-export]');if(!button||exporting)return;exporting=true;qa('[data-maker-export]').forEach(b=>b.disabled=true);const format=button.dataset.makerExport,name=filename();status.textContent='Preparo il tuo '+format.toUpperCase()+'…';try{const svg=E.render(state,{uid:'maker-export'}),info=E.info(state),blob=format==='svg'?new Blob([svg],{type:'image/svg+xml'}):await png(svg,info);download(blob,name+'.'+format);status.textContent='Pronto: '+name+'.'+format;}catch(error){status.textContent=error.message;}finally{exporting=false;paint();}});
q('#makerSave').addEventListener('click',()=>{const project={format:'hangover-object-maker',version:1,state};download(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),filename()+'.json');status.textContent='Progetto salvato. Usa Apri progetto per continuare a modificarlo.';});
q('#makerImport').addEventListener('change',async event=>{const input=event.target,file=input.files[0];if(!file)return;try{if(file.size>65536)throw Error('Questo file è troppo grande per essere un progetto HANGOVER.');const data=JSON.parse(await file.text());if(data.format!=='hangover-object-maker'||data.version!==1||!data.state||typeof data.state!=='object'||Array.isArray(data.state))throw Error('Scegli un progetto salvato da questo editor.');const next=D.normalize(data.state);remember();state=next;sync();paint();proposals();q('#makerPreset').value='';status.textContent='Progetto aperto. Tutte le scelte sono di nuovo modificabili.';}catch(e){status.textContent=e instanceof SyntaxError?'Il file non è un progetto valido. Scegli un file .json salvato qui.':e.message;}finally{input.value='';}});
sync();paint();proposals();
})();
