(function(){'use strict';
const A=window.HangoverSignage,section=document.querySelector('#segnaletica');if(!A||!section)return;
const stage=section.querySelector('#sgStage'),select=section.querySelector('#sgDesign'),palette=section.querySelector('#sgPalette'),input=section.querySelector('#sgText'),status=section.querySelector('#sgStatus'),samples=section.querySelector('#sgSamples');
let active=A.designs[0],state={palette:active.palette,label:active.label,arrow:active.arrow},mix=0;
for(const d of A.designs){const option=document.createElement('option');option.value=d.id;option.textContent=d.name+' / '+d.mood;select.append(option);const button=document.createElement('button');button.type='button';button.className='sg-sample';button.dataset.sg=d.id;button.setAttribute('aria-label','Prova '+d.name);button.setAttribute('aria-pressed',String(d===active));button.innerHTML=`<span class="sg-sample-art" aria-hidden="true">${A.render(d.id,{uid:'sample'})}</span><span class="sg-sample-copy"><span>${d.name}</span><span>${d.number} ↗</span></span><small>${d.mood.toUpperCase()} / ${d.support.toUpperCase()}</small>`;samples.append(button);}
for(const [id,p] of Object.entries(A.palettes)){const option=document.createElement('option');option.value=id;option.textContent=p.name;palette.append(option);}
const names={e:'Destra',se:'Basso a destra',s:'Giù',sw:'Basso a sinistra',w:'Sinistra',nw:'Alto a sinistra',n:'Su',ne:'Alto a destra'};
for(const [direction,symbol] of Object.entries(A.arrows)){const button=document.createElement('button');button.type='button';button.textContent=symbol;button.dataset.direction=direction;button.setAttribute('aria-label',names[direction]);button.setAttribute('aria-pressed','false');section.querySelector('#sgArrows').append(button);}
function paint(animate=false){stage.innerHTML=A.render(active.id,{...state,uid:'live'});stage.setAttribute('aria-label',state.label+' — '+active.name);section.querySelector('#sgName').textContent=active.name;section.querySelector('#sgDimensions').textContent=active.mmw+' × '+active.mmh+' mm / '+active.support;select.value=active.id;palette.value=state.palette;input.value=state.label;section.querySelectorAll('[data-direction]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.direction===state.arrow)));samples.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.sg===active.id)));stage.classList.toggle('is-changing',animate);}
function choose(id){active=A.designs.find(d=>d.id===id);state={palette:active.palette,label:active.label,arrow:active.arrow};paint(true);status.textContent=active.name+' / '+active.mood;}
select.addEventListener('change',()=>choose(select.value));palette.addEventListener('change',()=>{state.palette=palette.value;paint();status.textContent='Mix: '+active.name+' × '+A.palettes[state.palette].name;});
input.addEventListener('input',()=>{state.label=input.value.slice(0,22);stage.innerHTML=A.render(active.id,{...state,label:state.label||active.label,uid:'live'});stage.setAttribute('aria-label',(state.label||active.label)+' — '+active.name);status.textContent='Testo aggiornato.';});
section.querySelector('#sgArrows').addEventListener('click',e=>{const button=e.target.closest('[data-direction]');if(!button)return;state.arrow=button.dataset.direction;if(!state.label)state.label=active.label;paint();status.textContent='Direzione: '+names[state.arrow].toLowerCase()+'.';});
samples.addEventListener('click',e=>{const b=e.target.closest('[data-sg]');if(!b)return;choose(b.dataset.sg);section.querySelector('.sg-workbench').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});select.focus({preventScroll:true});});
section.querySelector('#sgReset').addEventListener('click',()=>choose(active.id));
section.querySelector('#sgMix').addEventListener('click',()=>{mix++;const colors=Object.keys(A.palettes);state.palette=colors[(colors.indexOf(state.palette)+3)%colors.length];state.arrow=Object.keys(A.arrows)[(mix*3)%8];paint(true);status.textContent='Mix: '+active.name+' × '+A.palettes[state.palette].name;});
function save(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
section.querySelector('#sgSvg').addEventListener('click',()=>{save(new Blob([A.render(active.id,{...state,label:state.label||active.label,uid:'export'})],{type:'image/svg+xml'}),'HANGOVER-SIGN-'+active.id+'.svg');status.textContent='SVG preparato.';});
section.querySelector('#sgPng').addEventListener('click',async()=>{const b=section.querySelector('#sgPng');b.disabled=true;const svg=A.render(active.id,{...state,label:state.label||active.label,uid:'export'}),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url;});const scale=2400/Math.max(active.mmw,active.mmh),c=document.createElement('canvas');c.width=Math.round(active.mmw*scale);c.height=Math.round(active.mmh*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/png'));if(!blob)throw Error();save(blob,'HANGOVER-SIGN-'+active.id+'.png');status.textContent='PNG preparato.';}catch{status.textContent='PNG non disponibile. Puoi scaricare lo SVG.';}finally{URL.revokeObjectURL(url);b.disabled=false;}});
paint();
})();
