(function(){
'use strict';
const data=window.HANGOVER_STUDIES;if(!data)return;
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
window.HANGOVER_GALLERIES={windows:data.windows,materials:data.materials,blueprint:data.blueprint,artists:window.HANGOVER_ARTISTS||[]};
function gallery(id,items,name){const container=$(id);if(!container)return;container.replaceChildren();items.forEach((item,i)=>{const f=document.createElement('figure');f.className='study-card';const b=document.createElement('button');b.dataset.gallery=name;b.dataset.galleryId=item.id;b.setAttribute('aria-label','Apri '+item.title);const img=window.HangoverImage.create(item);img.loading='lazy';img.decoding='async';img.width=item.width||1000;img.height=item.height||1250;b.append(img);const cap=document.createElement('figcaption'),title=document.createElement('span'),no=document.createElement('span');title.textContent=item.title;no.textContent=String(i+1).padStart(2,'0')+' ↗';cap.append(title,no);f.append(b,cap);if(item.colors){const swatches=document.createElement('div');swatches.className='material-colors';swatches.setAttribute('aria-hidden','true');item.colors.forEach(c=>{const dot=document.createElement('i');dot.style.background=c;swatches.append(dot)});cap.prepend(swatches);}container.append(f);});}
gallery('#windowsGrid',data.windows,'windows');gallery('#materialsGrid',data.materials,'materials');gallery('#blueprintGallery',data.blueprint,'blueprint');
function wireFilters(container,items,grid,group,field){$$(container+' button').forEach(b=>b.addEventListener('click',()=>{const selected=b.dataset.filter;const filtered=selected==='all'?items:items.filter(x=>x[field]===selected);$$(container+' button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));window.HANGOVER_GALLERIES[group]=filtered;gallery(grid,filtered,group);const count=$(grid+'Count');if(count)count.textContent=filtered.length+' / '+items.length;}));}
wireFilters('#windowsFilters',data.windows,'#windowsGrid','windows','theme');
const artists=window.HANGOVER_ARTISTS||[];gallery('#artistsGrid',artists,'artists');wireFilters('#artistsFilters',artists,'#artistsGrid','artists','region');
const board=$('#blueprintBoard');let letter='G',mode='construction';
const svgNS='http://www.w3.org/2000/svg';
function drawBlueprint(){const g=data.alphabet[letter],scale=620/141,w=g.width*scale,x=(1000-w)/2,y=185;board.replaceChildren();const svg=document.createElementNS(svgNS,'svg');svg.setAttribute('viewBox','0 0 1000 980');svg.setAttribute('role','img');svg.setAttribute('aria-label','Studio del glifo '+letter+', '+mode);const add=(tag,attrs,text)=>{const el=document.createElementNS(svgNS,tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));if(text)el.textContent=text;svg.append(el);return el;};
 add('rect',{width:1000,height:980,fill:'#0848cc'});
 if(mode==='construction'){for(let n=0;n<=1000;n+=40)add('path',{d:`M${n} 0V980M0 ${n}H1000`,stroke:'#bce3f5','stroke-width':1,opacity:.16});add('path',{d:`M${x} 75V910M${x+w} 75V910M60 ${y}H940M60 ${y+620}H940`,stroke:'#ff602e','stroke-width':2,fill:'none'});add('path',{d:`M${x} 115H${x+w}M${x} 104V126M${x+w} 104V126`,stroke:'#bce3f5','stroke-width':2});add('text',{x:500,y:97,fill:'#bce3f5','text-anchor':'middle','font-family':'monospace','font-size':19},g.width+' u');add('text',{x:925,y:500,fill:'#bce3f5','text-anchor':'end','font-family':'monospace','font-size':19},'141 u');}
 add('path',{d:g.d,transform:`translate(${x} ${y}) scale(${scale}) translate(-3 -3)`,fill:mode==='outline'?'none':'#bce3f5',stroke:'#bce3f5','stroke-width':mode==='outline'?0.7:0,'fill-rule':'evenodd'});
 if(mode==='construction')add('path',{d:g.d,transform:`translate(${x} ${y}) scale(${scale}) translate(-3 -3)`,fill:'none',stroke:'#0848cc','stroke-width':.2,'stroke-dasharray':'1 3'});
 add('text',{x:45,y:944,fill:'#bce3f5','font-family':'monospace','font-size':20,'letter-spacing':4},'HANGOVER / '+letter);add('text',{x:955,y:944,fill:'#bce3f5','font-family':'monospace','font-size':17,'text-anchor':'end'},String(Object.keys(data.alphabet).indexOf(letter)+1).padStart(2,'0')+' / 08');board.append(svg);$('#blueprintLetter').textContent=letter;
}
$$('[data-blueprint-letter]').forEach(b=>b.addEventListener('click',()=>{letter=b.dataset.blueprintLetter;$$('[data-blueprint-letter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));drawBlueprint();}));
$$('[data-blueprint-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.blueprintMode;$$('[data-blueprint-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));drawBlueprint();}));drawBlueprint();
$('#blueprintExport').addEventListener('click',()=>{const blob=new Blob([new XMLSerializer().serializeToString(board.querySelector('svg'))],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='HANGOVER-blueprint-'+letter+'-'+mode+'.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
})();
